const fetch = require('node-fetch');
const fs = require('fs');

neoxr.create(async (m, {
   client,
   text,
   prefix,
   command,
   Scraper, 
   Func
}) => {

try {
  const voiceIDs = {
"adele": "adele",
"among_us": "among_us",
"amr_diab": "amr_diab",
"amy_winehouse": "amy_winehouse",
"andrew_tate": "andrew_tate",
"angry_cat": "angry_cat",
"antimage_dota": "antimage_dota",
"ariana_grande": "ariana_grande",
"assala_nasri": "assala_nasri",
"aw_aw_cat": "aw_aw_cat",
"bad_bunny": "bad_bunny",
"bang_chan": "bang_chan",
"barbie_margot": "barbie_margot",
"barry_white": "barry_white",
"bart_simpson_en": "bart_simpson_en",
"bart_simpson_spa": "bart_simpson_spa",
"batman_christian_bale": "batman_christian_bale",
"batman_kevin_conroy": "batman_kevin_conroy",
"beyonce": "beyonce",
"bill_clinton": "bill_clinton",
"bill_kaulitz": "bill_kaulitz",
"billie_eilish": "billie_eilish",
"bjork": "bjork",
"bob_marley": "bob_marley",
"brazilian_lord_x": "brazilian_lord_x",
"britney_spears": "britney_spears",
"bruno_mars": "bruno_mars",
"butters_stotch": "butters_stotch",
"captain_america": "captain_america",
"car_burnout": "car_burnout",
"car_horn": "car_horn",
"cardi_b": "cardi_b",
"central_cee": "central_cee",
"chainsaw": "chainsaw",
"chapolin_colorado": "chapolin_colorado",
"chicken": "chicken",
"chorao": "chorao",
"chris_evans": "chris_evans",
"cogumelando": "cogumelando",
"counter_strike_radio": "counter_strike_radio",
"cristiano_ronaldo": "cristiano_ronaldo",
"crying_baby": "crying_baby",
"darth_vader": "darth_vader",
"darwin_watterson_tr": "darwin_watterson_tr",
"diego": "diego",
"dinho": "dinho",
"doc_hudson": "doc_hudson",
"doctor_strange": "doctor_strange",
"doja_cat": "doja_cat",
"dolores_umbridge": "dolores_umbridge",
"donald_duck": "donald_duck",
"donald_trump": "donald_trump",
"dota_crystal_maiden": "dota_crystal_maiden",
"dota_puck": "dota_puck",
"dota_rubick": "dota_rubick",
"dota_shadow_fiend": "dota_shadow_fiend",
"dota_slardar": "dota_slardar",
"dota_sniper": "dota_sniper",
"dota_sven": "dota_sven",
"drake": "drake",
"dwight_eisenhower": "dwight_eisenhower",
"eazy_e": "eazy_e",
"ed_sheeran": "ed_sheeran",
"elissa": "elissa",
"ella_fitzgerald": "ella_fitzgerald",
"elon_musk": "elon_musk",
"elsa": "elsa",
"elton_john": "elton_john",
"elvis_presley": "elvis_presley",
"eminem": "eminem",
"eren_yeager": "eren_yeager",
"eric_cartman": "eric_cartman",
"erkin_koray": "erkin_koray",
"ezreal_lol": "ezreal_lol",
"frank_sinatra": "frank_sinatra",
"franklin_roosevelt": "franklin_roosevelt",
"freddie_mercury": "freddie_mercury",
"fredo": "fredo",
"gabriel_diniz": "gabriel_diniz",
"garen_lol": "garen_lol",
"giveon": "giveon",
"goku_dragonball": "goku_dragonball",
"gollum": "gollum",
"goofy": "goofy",
"gumball_en": "gumball_en",
"gumball_spa": "gumball_spa",
"haerin": "haerin",
"hailey_bieber": "hailey_bieber",
"half_life_2_zombie": "half_life_2_zombie",
"han_jisung": "han_jisung",
"harry_styles": "harry_styles",
"heesung_hypen": "heesung_hypen",
"homer_simpson": "homer_simpson",
"hugh_jackman": "hugh_jackman",
"hulk": "hulk",
"hulk_hogan": "hulk_hogan",
"hwang_hyunjin": "hwang_hyunjin",
"iggy_azalea": "iggy_azalea",
"invoker_dota": "invoker_dota",
"iron_man": "iron_man",
"iron_man_brazil": "iron_man_brazil",
"itachi_uchiha": "itachi_uchiha",
"iu_idol": "iu_idol",
"jake_enhypen": "jake_enhypen",
"james_hetfield": "james_hetfield",
"janet_jackson": "janet_jackson",
"jay_enhypen": "jay_enhypen",
"jennie_idol": "jennie_idol",
"jeon_somi": "jeon_somi",
"jeongin": "jeongin",
"jerry_seinfeld": "jerry_seinfeld",
"jesse_pinkman": "jesse_pinkman",
"jhope_idol": "jhope_idol",
"jimin_idol": "jimin_idol",
"jimmy_fallon": "jimmy_fallon",
"jin_idol": "jin_idol",
"jisoo_idol": "jisoo_idol",
"joe_rogan": "joe_rogan",
"john_cena": "john_cena",
"joker": "joker",
"jonny_bravo": "jonny_bravo",
"juice_wrld": "juice_wrld",
"jungkook": "jungkook",
"justin_bieber": "justin_bieber",
"kanye_west": "kanye_west",
"katsuki_bakugo": "katsuki_bakugo",
"kemal_sunal": "kemal_sunal",
"kendall_roy": "kendall_roy",
"kendric_lamar": "kendric_lamar",
"kenny_mccormick": "kenny_mccormick",
"kim_chaewon": "kim_chaewon",
"kim_namjoon": "kim_namjoon",
"kim_seungmin": "kim_seungmin",
"kratos": "kratos",
"kufurbaz_haydo": "kufurbaz_haydo",
"kurt_cobain": "kurt_cobain",
"kyle_south_park": "kyle_south_park",
"lady_gaga": "lady_gaga",
"lana_del_rey": "lana_del_rey",
"lee_felix": "lee_felix",
"lee_know": "lee_know",
"leno_brega": "leno_brega",
"lightsaber": "lightsaber",
"liltay": "liltay",
"lisa_idol": "lisa_idol",
"lissandra_lol": "lissandra_lol",
"lizzo": "lizzo",
"lois_griffin": "lois_griffin",
"luciano_pavarotti": "luciano_pavarotti",
"lucoa": "lucoa",
"luke_skywalker": "luke_skywalker",
"madison_beer": "madison_beer",
"madonna": "madonna",
"manoel_gomes": "manoel_gomes",
"marceline": "marceline",
"marge_simpson": "marge_simpson",
"margot_robbie": "margot_robbie",
"marilia_mendonca": "marilia_mendonca",
"markiplier": "markiplier",
"martin_luther_king_jr": "martin_luther_king_jr",
"mauro_icardi": "mauro_icardi",
"meg_griffin": "meg_griffin",
"melanie_martinez": "melanie_martinez",
"messi": "messi",
"michael_jackson": "michael_jackson",
"michael_scott": "michael_scott",
"mickey_mouse": "mickey_mouse",
"miley_cyrus": "miley_cyrus",
"minecraft_door": "minecraft_door",
"minecraft_footsteps": "minecraft_footsteps",
"minecraft_pig": "minecraft_pig",
"minecraft_villager": "minecraft_villager",
"minions": "minions",
"mohammed_abdu": "mohammed_abdu",
"morgan_freeman": "morgan_freeman",
"morty_smith": "morty_smith",
"morty_smith_brazil": "morty_smith_brazil",
"mr_beast": "mr_beast",
"mr_krabs": "mr_krabs",
"muslum_gurses": "muslum_gurses",
"nami_one_piece": "nami_one_piece",
"nancy_ajram": "nancy_ajram",
"naruto_uzumaki": "naruto_uzumaki",
"nick_fury": "nick_fury",
"nicki_minaj": "nicki_minaj",
"nico_robin": "nico_robin",
"niki_enhypen": "niki_enhypen",
"obama": "obama",
"olivia_rodrigo": "olivia_rodrigo",
"one_piece_luffy": "one_piece_luffy",
"one_piece_sanji": "one_piece_sanji",
"perfect_cell": "perfect_cell",
"peter_griffin": "peter_griffin",
"phoebe_buffay": "phoebe_buffay",
"pikachu": "pikachu",
"pinkydoll": "pinkydoll",
"plankton": "plankton",
"pop_smoke": "pop_smoke",
"pudge_dota": "pudge_dota",
"raiden_shogun": "raiden_shogun",
"raluca_granola": "raluca_granola",
"randy_marsh": "randy_marsh",
"rashed_almaged": "rashed_almaged",
"richard_nixon": "richard_nixon",
"rick_sanchez": "rick_sanchez",
"ricky_gervais": "ricky_gervais",
"rihanna": "rihanna",
"roronoa_zoro": "roronoa_zoro",
"rose_idol": "rose_idol",
"roxanne_wolf": "roxanne_wolf",
"rubber_chicken": "rubber_chicken",
"rupaul": "rupaul",
"ryan_gosling": "ryan_gosling",
"sasuke_uchiha": "sasuke_uchiha",
"scary_little_girl": "scary_little_girl",
"selena_gomez": "selena_gomez",
"seo_changbin": "seo_changbin",
"shaco_lol": "shaco_lol",
"shakira": "shakira",
"sherine": "sherine",
"shrek": "shrek",
"shrek_donkey": "shrek_donkey",
"sia": "sia",
"sid": "sid",
"snoop_dogg": "snoop_dogg",
"spider_man_tobey_maguire": "spider_man_tobey_maguire",
"spongebob": "spongebob",
"squidward": "squidward",
"stewie_griffin": "stewie_griffin",
"suga_idol": "suga_idol",
"sunghoon_enhypen": "sunghoon_enhypen",
"sunoo_enhypen": "sunoo_enhypen",
"super_mario": "super_mario",
"super_mario_toad": "super_mario_toad",
"super_xandao": "super_xandao",
"sza": "sza",
"taylor_swift": "taylor_swift",
"ted_kaczynski": "ted_kaczynski",
"the_kid_laroi": "the_kid_laroi",
"the_notorious_big": "the_notorious_big",
"theodore_roosevelt": "theodore_roosevelt",
"thomas_shelby": "thomas_shelby",
"thor": "thor",
"tom_waits": "tom_waits",
"tony_soprano": "tony_soprano",
"toothbrush": "toothbrush",
"tow_mater": "tow_mater",
"travis_scott": "travis_scott",
"tuncel_kurtiz": "tuncel_kurtiz",
"tupac_shakur": "tupac_shakur",
"twentyone_savage": "twentyone_savage",
"venom": "venom",
"voldemort": "voldemort",
"walter_white": "walter_white",
"warwick_lol": "warwick_lol",
"washing_machine": "washing_machine",
"weeknd": "weeknd",
"whitney_houston": "whitney_houston",
"winnie_the_pooh": "winnie_the_pooh",
"winston_churchill": "winston_churchill",
"xxxtentacion": "xxxtentacion",
"yae_miko": "yae_miko",
"yungblud": "yungblud",
"yungwon_enhypen": "yungwon_enhypen",
"zeki_muren": "zeki_muren",
  // Add more voice IDs here
};
    let [voiceID, inputText] = text.split(" ", 2); // Split the text into two parts: voice ID and text
voiceID = voiceIDs[voiceID] || "default_voice_id"; 
if (!inputText) {
    return client.reply(m.chat, `Mana model suara/link youtube nya? Contoh:\n\n*.aicover yae_miko https://www.youtube.com/watch?v=Ci_zad39Uhw*\n\nUntuk melihat list model bisa dengan *.acl*`), m;
  }
  
  client.sendReact(m.chat, '🕒', m.key).then(() => client.reply(m.chat, '*Silahkan tunggu sebentar, lagu sedang dimuat*\n prosesnya bisa sampai 10 menit\ntergantung durasi lagu', m))

  let json = await Scraper.sovitsvoice(voiceID, inputText)
  
  client.sendMessage(m.chat, { audio: { url: `${json.result.audio}` }, ptt: true, mimetype: "audio/mpeg", fileName: "vn.mp3", waveform: [0,3,58,44,35,32,2,4,31,35,44,34,48,13,0,54,49,40,1,44,50,51,16,0,3,40,39,46,3,42,38,44,46,0,0,47,0,0,46,19,20,48,43,49,0,0,39,40,31,18,29,17,25,37,51,22,37,34,19,11,17,12,16,19], contextInfo: { externalAdReply: { title: 'TITLE:' + json.result.metadata.title, body: 'model_id:' + voiceID, thumbnailUrl: 'https://iili.io/JFpsikN.jpg', mediaType: 1, renderLargerThumbnail: true
      }}}, { quoted: m }) 
       } catch (e) {
         console.log(e)
         return client.reply(m.chat, '*terjadi eror*\npastikan link dan voice id benar!\nvoice id haruslah huruf kecil smua', m) 
         } 
}, {
 usage: ['aicover'],
   use: 'text',
   category: 'aimenu',
   limit: true
}, __filename)



neoxr.create(async (m, {
   client,
   text,
   prefix,
   command,
   Scraper, 
   Func
}) => {
    m.reply(`Ini list model Ai cover:

1. adele
2. among_us
3. amr_diab
4. amy_winehouse
5. andrew_tate
6. angry_cat
7. antimage_dota
8. ariana_grande
9. assala_nasri
10.	aw_aw_cat
11.	bad_bunny
12.	bang_chan
13.	barbie_margot
14.	barry_white
15.	bart_simpson_en
16.	bart_simpson_spa
17.	batman_christian_bale
18.	batman_kevin_conroy
19.	beyonce
20.	bill_clinton
21.	bill_kaulitz
22.	billie_eilish
23.	bjork
24.	bob_marley
25.	brazilian_lord_x
26.	britney_spears
27.	bruno_mars
28.	butters_stotch
29.	captain_america
30.	car_burnout
31.	car_horn
32.	cardi_b
33.	central_cee
34.	chainsaw
35.	chapolin_colorado
36.	chicken
37.	chorao
38.	chris_evans
39.	cogumelando
40.	counter_strike_radio
41.	cristiano_ronaldo
42.	crying_baby
43.	darth_vader
44.	darwin_watterson_tr
45.	diego
46.	dinho
47.	doc_hudson
48.	doctor_strange
49.	doja_cat
50.	dolores_umbridge
51.	donald_duck
52.	donald_trump
53.	dota_crystal_maiden
54.	dota_puck
55.	dota_rubick
56.	dota_shadow_fiend
57.	dota_slardar
58.	dota_sniper
59.	dota_sven
60.	drake
61.	dwight_eisenhower
62.	eazy_e
63.	ed_sheeran
64.	elissa
65.	ella_fitzgerald
66.	elon_musk
67.	elsa
68.	elton_john
69.	elvis_presley
70.	eminem
71.	eren_yeager
72.	eric_cartman
73.	erkin_koray
74.	ezreal_lol
75.	frank_sinatra
76.	franklin_roosevelt
77.	freddie_mercury
78.	fredo
79.	gabriel_diniz
80.	garen_lol
81.	giveon
82.	goku_dragonball
83.	gollum
84.	goofy
85.	gumball_en
86.	gumball_spa
87.	haerin
88.	hailey_bieber
89.	half_life_2_zombie
90.	han_jisung
91.	harry_styles
92.	heesung_hypen
93.	homer_simpson
94.	hugh_jackman
95.	hulk
96.	hulk_hogan
97.	hwang_hyunjin
98.	iggy_azalea
99.	invoker_dota
100. iron_man
101. iron_man_brazil
102. itachi_uchiha
103. iu_idol
104. jake_enhypen
105. james_hetfield
106. janet_jackson
107. jay_enhypen
108. jennie_idol
109. jeon_somi
110. jeongin
111. jerry_seinfeld
112. jesse_pinkman
113. jhope_idol
114. jimin_idol
115. jimmy_fallon
116. jin_idol
117. jisoo_idol
118. joe_rogan
119. john_cena
120. joker
121. jonny_bravo
122. juice_wrld
123. jungkook
124. justin_bieber
125. kanye_west
126. katsuki_bakugo
127. kemal_sunal
128. kendall_roy
129. kendric_lamar
130. kenny_mccormick
131. kim_chaewon
132. kim_namjoon
133. kim_seungmin
134. kratos
135. kufurbaz_haydo
136. kurt_cobain
137. kyle_south_park
138. lady_gaga
139. lana_del_rey
140. lee_felix
141. lee_know
142. leno_brega
143. lightsaber
144. liltay
145. lisa_idol
146. lissandra_lol
147. lizzo
148. lois_griffin
149. luciano_pavarotti
150. lucoa
151. luke_skywalker
152. madison_beer
153. madonna
154. manoel_gomes
155. marceline
156. marge_simpson
157. margot_robbie
158. marilia_mendonca
159. markiplier
160. martin_luther_king_jr
161. mauro_icardi
162. meg_griffin
163. melanie_martinez
164. messi
165. michael_jackson
166. michael_scott
167. mickey_mouse
168. miley_cyrus
169. minecraft_door
170. minecraft_footsteps
171. minecraft_pig
172. minecraft_villager
173. minions
174. mohammed_abdu
175. morgan_freeman
176. morty_smith
177. morty_smith_brazil
178. mr_beast
179. mr_krabs
180. muslum_gurses
181. nami_one_piece
182. nancy_ajram
183. naruto_uzumaki
184. nick_fury
185. nicki_minaj
186. nico_robin
187. niki_enhypen
188. obama
189. olivia_rodrigo
190. one_piece_luffy
191. one_piece_sanji
192. perfect_cell
193. peter_griffin
194. phoebe_buffay
195. pikachu
196. pinkydoll
197. plankton
198. pop_smoke
199. pudge_dota
200. raiden_shogun
201. raluca_granola
202. randy_marsh
203. rashed_almaged
204. richard_nixon
205. rick_sanchez
206. ricky_gervais
207. rihanna
208. roronoa_zoro
209. rose_idol
210. roxanne_wolf
211. rubber_chicken
212. rupaul
213. ryan_gosling
214. sasuke_uchiha
215. scary_little_girl
216. selena_gomez
217. seo_changbin
218. shaco_lol
219. shakira
220. sherine
221. shrek
222. shrek_donkey
223. sia
224. sid
225. snoop_dogg
226. spider_man_tobey_maguire
227. spongebob
228. squidward
229. stewie_griffin
230. suga_idol
231. sunghoon_enhypen
232. sunoo_enhypen
233. super_mario
234. super_mario_toad
235. super_xandao
236. sza
237. taylor_swift
238. ted_kaczynski
239. the_kid_laroi
240. the_notorious_big
241. theodore_roosevelt
242. thomas_shelby
243. thor
244. tom_waits
245. tony_soprano
246. toothbrush
247. tow_mater
248. travis_scott
249. tuncel_kurtiz
250. tupac_shakur
251. twentyone_savage
252. venom
253. voldemort
254. walter_white
255. warwick_lol
256. washing_machine
257. weeknd
258. whitney_houston
259. winnie_the_pooh
260. winston_churchill
261. xxxtentacion
262. yae_miko
263. yungblud
264. yungwon_enhypen
265. zeki_muren`
);
    
},{
usage: ['acl'],
   category: 'aimenu',
   limit: true
}, __filename)